---
abstract: 'near-real-time statistics from log files'
author:
  - 'Alex White <VVu@geekfarm.org>'
generated_by: 'Dist::Zilla version 1.092680'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Statistics
requires:
  Benchmark: 0
  Class::Std::Utils: 0
  Config::IniFiles: 0
  Data::Dumper: 0
  Date::Manip: 0
  ExtUtils::MakeMaker: 0
  File::Tail: 0
  File::Temp: 0
  IO::File: 0
  Log::Log4perl: 0
  Test::More: 0
  XML::Writer: 0
  YAML: 0
version: 0.050
